### ISSUE TITLE
I did not face this issue couple of days back, suddenly I am encountering this, can someone advise?

### ISSUE THREAD

**Issue by harish-nandirajendra** [terraform-aws-modules/terraform-aws-dms#16]
Error: 1 error occurred:* s3_settings must be set when engine_name = "s3"     with module.database_migration_service.aws_dms_endpoint.this["destination_2"],on .terraform/modules/database_migration_service/modules/terraform-aws-dms-master/main.tf  line 160, in resource "aws_dms_endpoint" "this":

**Comment by bryantbiggs** [comment]
again, please provide the details listed in the issue template https://github.com/terraform-aws-modules/terraform-aws-dms/issues/new?assignees=&labels=&template=bug_report.md
