### ISSUE TITLE
s3_settings must be set when engine_name = "s3" 

### ISSUE THREAD

**Issue by harish-nandirajendra** [terraform-aws-modules/terraform-aws-dms#17]
## Versions

- Module version [Required]: 1.5.1

- Terraform version:
0.15.4

# Description

I have downloaded the latest modules and referencing it using my local. Everything was working fine, all of a sudden this is happening, I don't know why.
I deployed multiple times, it was working fine like wine. I'm not sure why this error is coming up.

Error: 1 error occurred:* s3_settings must be set when engine_name = "s3"    
with module.database_migration_service.aws_dms_endpoint.this["destination_2"],on .terraform/modules/database_migration_service/modules/terraform-aws-dms-master/main.tf 
line 160, in resource "aws_dms_endpoint" "this":

## Expected behavior

Should not throw any issue. It was working fine previously.

## Actual behavior

S3 endpoints should be deployed successfully.

**Comment by harish-nandirajendra** [comment]
Need some help here, guys?

**Comment by sivapalaparthi84** [comment]
I am seeing the issue. Seems like something with Dynamic settings. Terraform is not identifying the S3_settings with dynamic settings on loop.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 1.5.2 :tada:

**Comment by bryantbiggs** [comment]
@harish-nandirajendra / @sivapalaparthi84 can you try using v1.5.2 and let us know if that resolves your issue
