### ISSUE TITLE
Creating AWS DMS task fails with: InvalidParameterValueException: TimestampColumnName cannot be an empty string.

### ISSUE THREAD

**Issue by casey-robertson-paypal** [terraform-aws-modules/terraform-aws-dms#24]
## Description

- [ x] ✋ I have searched the open/closed issues and my issue is not listed.

Module will not build a DMS task without passing a non-empty value for `timestamp_column_name` in the associated endpoint.  You can CREATE the endpoints by themselves without this value.  The error arises when creating DMS replication tasks.

## Versions

- Module version [Required]: 1.5.3

- Terraform version:
Terraform v1.2.7
- Provider version(s):
Terraform v1.2.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.30.0
+ provider registry.terraform.io/hashicorp/time v0.8.0

## Reproduction Code [Required]

```
// S3 endpoint target definition
    s3-target-main-ongoing-csv = {
      endpoint_id   = "hr-pypl-s3-target-${var.environment}-ongoing-csv"
      endpoint_type = "target"
      engine_name   = "s3"
      ssl_mode      = "none"

      s3_settings = {
        bucket_folder             = "ongoing-csv"
        bucket_name               = local.bucket_name # to avoid https://github.com/hashicorp/terraform/issues/4149
        data_format               = "csv"
        encryption_mode           = "SSE_S3"
        // external_table_definition = file("configs/s3_table_definition.json")
        service_access_role_arn   = "arn:${data.aws_partition.current.partition}:iam::${data.aws_caller_identity.current.account_id}:role/${local.name}-s3" # to avoid https://github.com/hashicorp/terraform/issues/4149
      }

       tags                        =  merge(tomap({ EndpointType = "source" }), local.tags)
    }

// Task definition
postgres-db-main-ongoing-a-csv = {
      replication_task_id       = "hr-pypl-edl-${local.name}-db-main-ongoing-a-csv"
      migration_type            = "cdc"
      replication_task_settings = file("./dms_config/task_settings/task-settings-ongoing.json")
      table_mappings            = file("./dms_config/table_mappings/table-mappings-ongoing-a.json")
      source_endpoint_key       = "postgresql-source-db-main"
      target_endpoint_key       = "s3-target-main-ongoing-csv"
      tags                        =  merge(tomap({ Task = "Dev-DB-CDC-to-S3" }), local.tags)
    }
```

Invoke the module leveraging a bucket and role that was created.  This worked earlier today - came back to make some changes to the endpoint configs and on subsequent runs it fails now.  Settings above are pre-change - exactly as earlier when the replication tasks successfully created.  

## Expected behavior

DMS replication task created that leverages the above S3 target endpoint

## Actual behavior

AWS API throws an error about empty config value

### Terminal Output Screenshot(s)

```
Error: error creating DMS Replication Task (hr-pypl-edl-dms-dev-db-main-ongoing-a-csv): InvalidParameterValueException: TimestampColumnName cannot be an empty string.
│       status code: 400, request id: 0428df1b-f6da-46f1-96da-6aea1182b7d6
│ 
│   with module.database_migration_service.aws_dms_replication_task.this["postgres-db-main-ongoing-a-csv"],
│   on .terraform/modules/database_migration_service/main.tf line 289, in resource "aws_dms_replication_task" "this":
│  289: resource "aws_dms_replication_task" "this" {
```

## Additional context

Yesterday and today this module, endpoints (source and target S3) and jobs created without issue.  Now it only runs if I supply what should be an optional `timestamp_column_name` config value per this documentation: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_endpoint#timestamp_column_name

If I add a value such as `timestamp_column_name = "foo"` to the S3 endpoint configuration, the plan and apply run without issue.  But per the Terraform and API docs this should be an optional value.  I'm at a loss.

**Comment by skolsuper** [comment]
Closed without acknowledgement, what an annoying bot
