### ISSUE TITLE
Multiple modules, one for each resource

### ISSUE THREAD

**Issue by kstavropoulos-fl** [terraform-aws-modules/terraform-aws-dms#25]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.

  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
Would like to be able to create each resource separately. Meaning - Replication instance, replication endpoint, replication task, subnet group.

## Describe the solution you'd like.
I'm thinking sub-modules is probably the best way for this.

## Describe alternatives you've considered.
Adding `create_{resource}` variables.

## Additional context
Would you be open to doing this change? If so, would it be a major version bump? I could start working on this.

**Comment by antonbabenko** [comment]
Hi!

The way this module is written now is already capable of doing what you described in some cases. There are already multiple `create_...` flags, but `aws_dms_replication_instance`, being the main resource of the module, is currently controls everything that will be created by the module.

There is no need to make separate submodules for each resource, but instead, I suggest that we add another (more granular) flag(s) for resources that don't have it and update the code in the examples to show how partial creation of resources can be achieved.

It is also important to keep it as backward-compatible as possible. No need to make a major release for this.

PR is welcome. :)

**Comment by kstavropoulos-fl** [comment]
Sounds good to me! Will make some time for new `create_...` variables and open a PR :)

**Comment by bryantbiggs** [comment]
What is the motivation for creating separate resources - could you describe the use cases? Typically a module is intended to provide functionality from multiple resources and we avoid having modules that wrap single resources so I am wondering what you are trying to achieve by looking at individual modules per resource?

**Comment by kstavropoulos-fl** [comment]
Sure. My thinking and wanting was to structure these resources in separate directories and .hcl files. 
Perhaps like:
```
└── dms
    ├── endpoints
    │   ├── my-source-endpoint
    │   │     └── terragrunt.hcl
    │   ├── my-source-endpoint-2
    │   │     └── terragrunt.hcl
    │   └── my-target-endpoint
    │         └── terragrunt.hcl
    ├── instances
    │    ├── my-replication-instance
    │    │   └── terragrunt.hcl
    │    └── my-replication-instance-2
    │         └── terragrunt.hcl
    └── tasks
           ├── my-dms-task
           │   ├── mappings.json
           │   ├── repl_task_settings.json
           │   └── terragrunt.hcl
           └── my-dms-task-2
                ├── mappings.json
                ├── repl_task_settings.json
                └── terragrunt.hcl
```

You are absolutely correct in your comment in the linked PR about `var.create_endpoints`, similarly for `var.create_repl_task`, I did a hasty job there, and wanted to think about it and test it more, so I put it with `[WIP]` soon after opening it until I had time.

Does the `var.create_repl_task` boolean make sense to you?

If we have that, then the above structure is possible.

**Comment by antonbabenko** [comment]
Seeing such structure and terragrunt, I'd like to mention that you can use `wrappers` to manage multiple resources of the same type in fewer `terragrunt.hcl` files. We don't have wrappers in this module yet, but it is just one line to add them if you think it will help you.

Look into [`s3-bucket/wrappers`](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/tree/master/wrappers#usage-with-terragrunt), for example, to get an idea of this approach.

Your project can be updated to have just one `terragrunt.hcl` for all DMS resources, which will get a big map of `items` where everything will be defined.
