### ISSUE TITLE
Allow IAM role names to be configurable (such as with prefixes)

### ISSUE THREAD

**Issue by stv-io** [terraform-aws-modules/terraform-aws-dms#32]
## Is your request related to a problem? Please describe.

Currently the IAM role names are hard-coded, so that multiple deployments of this module into the same account causes a conflict on the second deployment.

 - https://github.com/terraform-aws-modules/terraform-aws-dms/blob/ddb33cbc7a39add9d331cef49206d1aa80d14541/main.tf#L74
 - https://github.com/terraform-aws-modules/terraform-aws-dms/blob/ddb33cbc7a39add9d331cef49206d1aa80d14541/main.tf#L88
 - https://github.com/terraform-aws-modules/terraform-aws-dms/blob/ddb33cbc7a39add9d331cef49206d1aa80d14541/main.tf#L60

## Describe the solution you'd like.
 - The role names are optionally prefixed with an identifier provided as a variable. Or the whole name is configurable.

## Describe alternatives you've considered.
 - Forking and implementing the variable.

## Additional context
I've seen this implemented in other aws modules, such as the EKS one - https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/main.tf#L231

Also, copied from a similar issue 🙃 - Friends don't want friends to fork terraform-aws-modules. 😄

**Comment by bryantbiggs** [comment]
this is not something that is configurable - please see the links provided https://github.com/terraform-aws-modules/terraform-aws-dms/blob/ddb33cbc7a39add9d331cef49206d1aa80d14541/main.tf#L12

this is also stated on the provider docs https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_replication_instance
