### ISSUE TITLE
Ignore_headers_row changed to ignore_header_rows

### ISSUE THREAD

**Issue by Johnyang12345** [terraform-aws-modules/terraform-aws-dms#38]
Hi,

In main.tf line 269:
      ignore_headers_row                = lookup(s3_settings.value, "ignore_headers_row", null)

ignore_headers_row was changed to ignore_header_rows in https://registry.terraform.io/providers/hashicorp/aws/4.65.0/docs/resources/dms_endpoint

Thanks,
John

**Comment by brunodasilvalenga** [comment]
Up

**Comment by nimish** [comment]
Is there a maintainer on this project? @antonbabenko this is a necessary fix for this module to work with aws >= 5

**Comment by bryantbiggs** [comment]
There are a few changes we need to make to support v5.0 of the AWS provider. Until we make those changes in a breaking change (major version) for this module, you can pin the version of the provider that you use to < 5.0

**Comment by nimish** [comment]
> There are a few changes we need to make to support v5.0 of the AWS provider. Until we make those changes in a breaking change (major version) for this module, you can pin the version of the provider that you use to < 5.0

Hmm, we cannot do this. We'll have to fork this with a temp fix in the meantime.

**Comment by igorjanevski** [comment]
Up!
Please fix this, we are stuck with the issue!

**Comment by arthur-ventura** [comment]
Up!

**Comment by DodgeCamaro** [comment]
Up

**Comment by tiagoflino** [comment]
Up!

**Comment by josep-pla-jt** [comment]
Up!

**Comment by johnlds-dnx** [comment]
up

**Comment by damianarata** [comment]
Up

**Comment by crisboarna** [comment]
Up

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.0.0 :tada:

**Comment by brunodasilvalenga** [comment]
Really appreciate it @antonbabenko
