### ISSUE TITLE
Examples have stopped working 

### ISSUE THREAD

**Issue by cslattery117** [terraform-aws-modules/terraform-aws-dms#43]
## Description
This is due to a provider change to 5.0 
 See
https://www.reddit.com/r/Terraform/comments/13uc728/an_issue_with_terraform_module_320/

Fix is to push the AWS provider version to 5.0, but this then brings a second issue with EBS volume size being removed from the Kafka provider. 

Recommend these be revisited to update the example to work with current providers, please.  

thanks. 

Should not be too difficult !

**Comment by cslattery117** [comment]
Yes 
1. Update aws provider to 5.0
2. Update MSK cluster to 2.1.0 as per latest version and remove ebs vol size 
3. change scram config wording 

now terraform plan works

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.0.0 :tada:
