### ISSUE TITLE
do the module support aws_dms_replication_config? 

### ISSUE THREAD

**Issue by sergiovr123** [terraform-aws-modules/terraform-aws-dms#53]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
i need to enable aws_dms_replication_config to setup serverless feature

## Describe the solution you'd like.
i would like to have a way to enable aws_dms_replication_config

## Describe alternatives you've considered.
fork the repo and enable it

**Comment by roelywoely** [comment]
It would be great if this is supported.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.2.0 :tada:
