### ISSUE TITLE
All the tasks are recreated if we add a new endpoint. 

### ISSUE THREAD

**Issue by jogendrajangid-tryjeeves** [terraform-aws-modules/terraform-aws-dms#62]
## Description

We are using the module to create the DMS instance, endpoint, and tasks. if we are adding a new endpoint for a new task requirement.
At the time of applying the changes, the endpoint will be create but all the current tasks also recreating. There is no change in task configuration. we are just adding a new endpoint.

- [ Done ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: v2.2.0

- Terragrunt version 0.57.0

- Provider version(s):
   hashicorp/aws >= 5.32
 

## Reproduction Code [Required]

Steps
1. Create new dms instance, endpoint and tasks using this module
2.  Add new endpoint to configuration
3. Try to apply the changes. 

## Expected behavior
The new endpoint only need to be created.

## Actual behavior
New endpoint are creating but same time we can see the all the tasks are recreating.

### Terminal Output Screenshot(s)
```
  # aws_dms_replication_task.this["track_to_s3"] must be replaced
-/+ resource "aws_dms_replication_task" "this" {
      + cdc_start_position        = (known after apply)
      ~ id                        = "development-import-mysql-tracking-to-s3" -> (known after apply)
      ~ replication_task_arn      = "arn:aws:dms:us-east-2:xxxxxxxxx:task:xyz" -> (known after apply)
      ~ replication_task_settings = jsonencode(
          ~ {
              ~ ControlTablesSettings               = {
                  - historyTimeslotInMinutes      = 5
                    # (6 unchanged attributes hidden)
                }
              ~ Logging                             = {
                  - CloudWatchLogGroup  = "dms-tasks-redshift-datasync"
                  - CloudWatchLogStream = "dms-task-syz"
                  - EnableLogContext    = false
                    # (2 unchanged attributes hidden)
                }
                # (12 unchanged attributes hidden)
            }
        )
      ~ source_endpoint_arn       = "arn:aws:dms:us-east-2:xxxxxxxxxxx:endpoint:xyz" # forces replacement -> (known after apply) # forces replacement
      ~ status                    = "running" -> (known after apply)
        tags                      = {
            "Environment" = "development"
            "Task"        = "development-import-mysql-tracking-to-s3"
            "Terraform"   = "true"
        }
      ~ target_endpoint_arn       = "arn:aws:dms:us-east-2:xxxx:endpoint:xyz" # forces replacement -> (known after apply) # forces replacement
        # (6 unchanged attributes hidden)
    }
```

**Comment by bryantbiggs** [comment]
This is just down to the DMS API - you can see from these two lines:

```
~ source_endpoint_arn       = "arn:aws:dms:us-east-2:xxxxxxxxxxx:endpoint:xyz" # forces replacement -> (known after apply) # forces replacement
...
~ target_endpoint_arn       = "arn:aws:dms:us-east-2:xxxx:endpoint:xyz" # forces replacement -> (known after apply) # forces replacement
```

Any time you change a source or target endpoint for a task, the API requires the task to be replaced.

**Comment by jogendrajangid-tryjeeves** [comment]
> This is just down to the DMS API - you can see from these two lines:
> 
> ```
> ~ source_endpoint_arn       = "arn:aws:dms:us-east-2:xxxxxxxxxxx:endpoint:xyz" # forces replacement -> (known after apply) # forces replacement
> ...
> ~ target_endpoint_arn       = "arn:aws:dms:us-east-2:xxxx:endpoint:xyz" # forces replacement -> (known after apply) # forces replacement
> ```
> 
> Any time you change a source or target endpoint for a task, the API requires the task to be replaced.

In our case we have't make any changes to current tasks. Just added a new endpoint but still in That case all the current tasks force to replace.

**Comment by elchesco** [comment]
+1

**Comment by juanjesus-jeeves** [comment]
+1
