### ISSUE TITLE
Invalid function argument error when using merge method

### ISSUE THREAD

**Issue by yuekui** [terraform-aws-modules/terraform-aws-dms#64]
## Description

To conditionally create an endpoint, we plan to use a merge method combined with a ternary expression. However, this approach may lead to an 'Invalid function argument' error because the lookup function might return a null value, which differs from the expected default type `[]`.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions
- Terraform version:
1.5.7
- Provider version(s):
hashicorp/aws v5.48.0

## Reproduction Code [Required]
```terraform
locals {
  is_additional_task_needed = true
}

module "dms_aurora_postgresql_aurora_mysql" {
  # Endpoints
  endpoints = merge({
    postgresql-destination = {
      ...
    },local.is_additional_task_needed ? {
    mysql-source = {
      database_name = "foo"
      ...
    } } : {}
  )
```

## Expected behavior

Endpoints should be created successfully

## Actual behavior

Invalid function argument errors were raised when trying to lookup settings of each value

### Terminal Output Screenshot(s)

![image](https://github.com/terraform-aws-modules/terraform-aws-dms/assets/2561450/019fa7c9-ca36-407b-801c-e6743890aa9d)

## Additional context
I've created a [PR](https://github.com/terraform-aws-modules/terraform-aws-dms/pull/63) and added the conditional endpoints in example

**Comment by yuekui** [comment]
Hi @bryantbiggs , it would be great if you could review this when you have a chance. Thanks!

**Comment by yuekui** [comment]
Just re-opened the PR, waiting for review

**Comment by bryantbiggs** [comment]
this looks like a dynamic workspace use issue, not a module issue. if you want to do this sort of dynamic "if this, then that", then you should use map comprehension instead of a conditional on the map object
